fixtures:
  repositories:
    stdlib: 
      repo: 'https://github.com/puppetlabs/puppetlabs-stdlib.git'
      ref: '5.2.0'
    concat: 'https://github.com/puppetlabs/puppetlabs-concat.git'
  symlinks:
    zypprepo: "#{source_dir}"
